In [12]:
import numpy as np
import pandas as np

In [ ]:
!pip install bert-extractive-summarizer

     |████████████████████████████████| 2.9 MB 5.7 MB/s 
     |████████████████████████████████| 596 kB 59.7 MB/s 
     |████████████████████████████████| 3.3 MB 44.2 MB/s 
     |████████████████████████████████| 56 kB 3.8 MB/s 
     |████████████████████████████████| 895 kB 71.2 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [ ]:
from summarizer import Summarizer

In [ ]:
covid_text = open('covid.txt','r').read()

In [ ]:
model = Summarizer()
result = model(covid_text,min_length=20)

Downloading:   0%|          | 0.00/571 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.25G [00:00<?, ?B/s]

Some weights of the model checkpoint at bert-large-uncased were not used when initializing BertModel: ['cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


Downloading:   0%|          | 0.00/226k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/455k [00:00<?, ?B/s]

In [ ]:
result

'The speed of transmission is an important point of difference between the two viruses. However, estimates for both COVID-19 and influenza viruses are very context and time-specific, making direct comparisons more difficult.'

In [ ]:
summary = ' '.join(result)

In [ ]:
summary

'T h e   s p e e d   o f   t r a n s m i s s i o n   i s   a n   i m p o r t a n t   p o i n t   o f   d i f f e r e n c e   b e t w e e n   t h e   t w o   v i r u s e s .   H o w e v e r ,   e s t i m a t e s   f o r   b o t h   C O V I D - 1 9   a n d   i n f l u e n z a   v i r u s e s   a r e   v e r y   c o n t e x t   a n d   t i m e - s p e c i f i c ,   m a k i n g   d i r e c t   c o m p a r i s o n s   m o r e   d i f f i c u l t .'

In [ ]:
covid_text

'\nThe speed of transmission is an important point of difference between the two viruses. Influenza has a shorter median incubation period (the time from infection to appearance of symptoms) and a shorter serial interval (the time between successive cases) than COVID-19 virus. The serial interval for COVID-19 virus is estimated to be 5-6 days, while for influenza virus, the serial interval is 3 days. This means that influenza can spread faster than COVID-19. \n\nFurther, transmission in the first 3-5 days of illness, or potentially pre-symptomatic transmission –transmission of the virus before the appearance of symptoms – is a major driver of transmission for influenza. In contrast, while we are learning that there are people who can shed COVID-19 virus 24-48 hours prior to symptom onset, at present, this does not appear to be a major driver of transmission. \n\nThe reproductive number – the number of secondary infections generated from one infected individual – is understood to be bet

## Bulding the model

In [22]:
import tensorflow_hub as hub
from keras import layers
import tensorflow_text as text

In [21]:
!pip install tensorflow_text

     |████████████████████████████████| 4.4 MB 5.2 MB/s 


In [50]:
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"

In [51]:
bert_preprocess_model = hub.KerasLayer(preprocess_url)
bert_encoder_model = hub.KerasLayer(encoder_url)

In [25]:
sent = ['he is a good boy','she is a good girl','he is a bad boy']

In [26]:
preprocessed = bert_preprocess_model(sent)

In [27]:
preprocessed.keys()

dict_keys(['input_type_ids', 'input_mask', 'input_word_ids'])

In [28]:
preprocessed['input_word_ids']

<tf.Tensor: shape=(3, 128), dtype=int32, numpy=
array([[ 101, 2002, 2003, 1037, 2204, 2879,  102,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0],
       [ 101, 2016, 2003, 1037, 2204, 2611,  102,    0,    0,    0,    0,
           0,

In [29]:
encoded = bert_encoder_model(preprocessed)

In [30]:
encoded.keys()

dict_keys(['pooled_output', 'default', 'sequence_output', 'encoder_outputs'])

In [32]:
encoded['pooled_output']

<tf.Tensor: shape=(3, 768), dtype=float32, numpy=
array([[-0.85943204, -0.4148627 , -0.71187615, ..., -0.37655276,
        -0.6816058 ,  0.8787798 ],
       [-0.87792015, -0.3794878 , -0.57588845, ..., -0.10914135,
        -0.6796491 ,  0.9089936 ],
       [-0.8479175 , -0.40923095, -0.5687729 , ..., -0.1769114 ,
        -0.65430003,  0.8645711 ]], dtype=float32)>

In [33]:
vector1 = encoded['pooled_output'][0]
vector2 = encoded['pooled_output'][1]
vector3 = encoded['pooled_output'][2]

In [35]:
from sklearn.metrics.pairwise import cosine_similarity

In [36]:
cs1 = cosine_similarity([vector1],[vector2])
cs2 = cosine_similarity([vector2],[vector3])
cs3 = cosine_similarity([vector1],[vector3])

In [37]:
print(cs1)

[[0.991997]]


In [38]:
print(cs2)

[[0.9911562]]


In [39]:
print(cs3)

[[0.99004745]]


In [46]:
text_corpus = 'Influenza has a shorter median incubation period (the time from infection to appearance of symptoms) and a shorter serial interval than COVID-19 virus. The serial interval for COVID-19 virus is estimated to be 5-6 days, while for influenza virus, the serial interval is 3 days. This means that influenza can spread faster than COVID-19. Further, transmission in the first 3-5 days of illness, or potentially pre-symptomatic transmission –transmission of the virus before the appearance of symptoms – is a major driver of transmission for influenza. In contrast, while we are learning that there are people who can shed COVID-19 virus 24-48 hours prior to symptom onset, at present, this does not appear to be a major driver of transmission.'

In [47]:
count = 0
for i in text_corpus.split(' '):
  count+=1

In [48]:
count

119

In [53]:
preprocessed_text = bert_preprocess_model([text_corpus])

In [54]:
encoded_text = bert_encoder_model(preprocessed_text)

In [57]:
vector_of_corpus = encoded_text['pooled_output']

In [78]:
vector_of_corpus.

<tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[-0.82020706, -0.71162957, -0.9610132 ,  0.37239084,  0.8438916 ,
        -0.52430946, -0.50336313,  0.5879254 , -0.91108257, -0.99991846,
        -0.69530654,  0.9617434 ,  0.94929475,  0.51623654,  0.5477869 ,
        -0.45229408,  0.07507989, -0.55753434,  0.41140497,  0.91709775,
         0.43958792,  0.99999905, -0.4622987 ,  0.6379905 ,  0.56359446,
         0.9926872 , -0.68933415,  0.72796917,  0.83568615,  0.6126168 ,
         0.12093206,  0.48534682, -0.9825011 , -0.40120205, -0.9758681 ,
        -0.9554166 ,  0.6478666 , -0.3925985 , -0.21309346, -0.2801414 ,
        -0.6086518 ,  0.5724905 ,  0.99997115, -0.36532646,  0.68208605,
        -0.27188066, -0.9999995 ,  0.31879786, -0.39929238,  0.95912933,
         0.92730874,  0.98356724,  0.45266443,  0.6232694 ,  0.686016  ,
        -0.8713355 ,  0.16391192,  0.32484263, -0.5373567 , -0.6843958 ,
        -0.69403166,  0.607241  , -0.8762638 , -0.5733665 ,  0.9318678 ,
 

In [60]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [61]:
sentences_tokens = nltk.sent_tokenize(text_corpus)

In [62]:
sentences_tokens

['Influenza has a shorter median incubation period (the time from infection to appearance of symptoms) and a shorter serial interval than COVID-19 virus.',
 'The serial interval for COVID-19 virus is estimated to be 5-6 days, while for influenza virus, the serial interval is 3 days.',
 'This means that influenza can spread faster than COVID-19.',
 'Further, transmission in the first 3-5 days of illness, or potentially pre-symptomatic transmission –transmission of the virus before the appearance of symptoms – is a major driver of transmission for influenza.',
 'In contrast, while we are learning that there are people who can shed COVID-19 virus 24-48 hours prior to symptom onset, at present, this does not appear to be a major driver of transmission.']

In [65]:
preprocessed_sent = bert_preprocess_model(sentences_tokens)

In [67]:
encoded_sent = bert_encoder_model(preprocessed_sent)

In [71]:
encoded_sent.keys()

dict_keys(['pooled_output', 'encoder_outputs', 'default', 'sequence_output'])

In [73]:
encoded_sent['pooled_output'][0]

<tf.Tensor: shape=(768,), dtype=float32, numpy=
array([-0.7131898 , -0.56050396, -0.9036959 ,  0.3431906 ,  0.8131127 ,
       -0.3435421 , -0.47681224,  0.42321095, -0.7738512 , -0.99993277,
       -0.42024142,  0.9181198 ,  0.9373497 ,  0.24191669,  0.28770226,
       -0.5181523 , -0.35054526, -0.3037576 ,  0.1968084 ,  0.8741712 ,
        0.35981494,  0.9999975 , -0.5205341 ,  0.4762948 ,  0.3046149 ,
        0.9571139 , -0.63518727,  0.5451946 ,  0.78816533,  0.7843985 ,
        0.16445433,  0.21175404, -0.9858807 , -0.08049226, -0.93667984,
       -0.947552  ,  0.45206788, -0.3901288 , -0.11884613, -0.16094667,
       -0.6439906 ,  0.43892306,  0.9999751 , -0.52701557,  0.7364568 ,
       -0.13646348, -0.9999921 ,  0.11068229, -0.5143648 ,  0.8912225 ,
        0.8047825 ,  0.92145824,  0.25774783,  0.50572854,  0.55349064,
       -0.8845447 ,  0.00979453,  0.11240636, -0.43503714, -0.6274159 ,
       -0.60009587,  0.39626732, -0.8085093 , -0.63095033,  0.8928511 ,
        0.674946

In [68]:
list_token = []

In [100]:
for (i,j) in enumerate(encoded_sent['pooled_output']):
  vect = encoded_sent['pooled_output'][i]
  cs = cosine_similarity([vect],vector_of_corpus)
  list_token.append((cs,i))

In [101]:
print(list_token)

[(array([[0.97036016]], dtype=float32), 0), (array([[0.8902209]], dtype=float32), 1), (array([[0.90760255]], dtype=float32), 2), (array([[0.90591913]], dtype=float32), 3), (array([[0.934549]], dtype=float32), 4)]


In [115]:
token_index = [0,2,4]

In [126]:
summary_corpus = ''
for i in token_index:
  summary_corpus += sentences_tokens[i]
  summary_corpus += ' '

In [127]:
summary_corpus

'Influenza has a shorter median incubation period (the time from infection to appearance of symptoms) and a shorter serial interval than COVID-19 virus. This means that influenza can spread faster than COVID-19. In contrast, while we are learning that there are people who can shed COVID-19 virus 24-48 hours prior to symptom onset, at present, this does not appear to be a major driver of transmission. '